name: learn-github-actions
on: [push]
jobs:
  build-project:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: .\build.ps1
      - run: echo ${{ github.run_id }}
      - run: echo ${{ github.run_number }}
